camera_list: [left, down]

left:
    ID: "Camera_Depth_left"
    outputShaderType: 2 #Depth
    hasCollisionCheck: true
    doesLandMarkVisCheck: false

right:
    ID: "Camera_RGB_right"
    outputShaderType: -1 #rgb
    hasCollisionCheck: true
    doesLandMarkVisCheck: false
    baseline_translation: 0.10

down:
    ID: "Camera_Depth_down"
    outputShaderType: 2 #rgb
    hasCollisionCheck: false
    doesLandMarkVisCheck: false