camera_list: [left_rgb_blurred, left_depth, down_depth, down_rgb_blurred, left_segmented, down_segmented]

# enum outputShaderType {
#   RGB = -1,
#   InstanceID = 0,
#   SemanticID = 1,
#   DepthCompressed = 2,
#   DepthMultiChannel = 3,
#   SurfaceNormals =4
#   grayscale=5
# }

# Depth
left_depth:
    tf: left
    ID: "Camera_Left_Depth"                     
    outputShaderType: 2         
    hasCollisionCheck: false
    doesLandMarkVisCheck: false


down_depth:
    tf: down
    ID: "Camera_Down_Depth"
    outputShaderType: 2 
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

# RGB Blurred
left_rgb_blurred:
    tf: left
    ID: "Camera_Left_RGB"
    motionBlurPercent: 1.0                     
    outputShaderType: -1        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

down_rgb_blurred:
    tf: down
    ID: "Camera_Down_RGB"
    motionBlurPercent: 1.0                     
    outputShaderType: -1        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

# Grayscale
left_gray:
    tf: left
    ID: "Camera_Left_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

right_gray:
    tf: right
    ID: "Camera_Right_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

down_gray:
    tf: down
    ID: "Camera_Down_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

# Segmentation
left_segmented:
    tf: left
    ID: "Camera_Left_Segmented"
    motionBlurPercent: 0.0                     
    outputShaderType: 1        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false

down_segmented:
    tf: down
    ID: "Camera_Down_Segmented"
    motionBlurPercent: 0.0                     
    outputShaderType: 1        
    hasCollisionCheck: false
    doesLandMarkVisCheck: false